language: python
dist: trusty
sudo: false
addons:
  firefox: "45.4.0esr"
python:
  - "2.7"
  - "3.6"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - wget https://www.sqlite.org/2019/sqlite-autoconf-3270200.tar.gz
  - tar xvf sqlite-autoconf-3270200.tar.gz
  - pushd sqlite-autoconf-3270200 && ./configure --prefix=/usr && make && sudo make install && popd
before_script:
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt
  - pip install coveralls
  - cd OpenOversight
script:
  - py.test -v -n 4 --dist=loadfile --cov=app
  - cd .. && flake8 --ignore=E501,E722
after_success:
  - coveralls
